# Generated by Django 2.1.4 on 2019-01-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(max_length=32)),
                ('wallet_money', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_type', models.CharField(max_length=32)),
                ('operate_account', models.CharField(max_length=32)),
                ('operate_amount', models.FloatField(default=0)),
                ('operate_time', models.DateTimeField()),
                ('remarks', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField()),
                ('register_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('email', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=32)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.UserInfo'),
        ),
        migrations.AddField(
            model_name='money',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.UserInfo'),
        ),
    ]
